theme: jekyll-theme-leap-day
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
title: ProMaGen documentation
description: pro-ject ma-nager gen-erator
show_downloads: true
